### ISSUE TITLE
New Hotend

### ISSUE THREAD

**Issue by MichaelMartinez** [askmurphy/My-extreme-modded-Craftbot-3D-printer#1]
Just curious as to why you went with the Craftbot hotend... I have a CB+ and I am looking to either build a new printer or completely redo the CB+ like you have done. 

I would like to run Klipper and MainsailOS. Upgrade to a Voron/Ratrig style extruder/hotend combo. What do you think? I am guessing we could get some pretty wild print speeds out of this machine with a new extruder/hotend combo...

**Comment by askmurphy** [comment]
Hi Michael!
I have used the upgraded CB hotend because that was the most easy way to fix the old hotend: this new hotend is much better then the original version.  But indeed, you can improve it a lot more if you change the hotend and extruder for somesing else: the Orbi-extruder with a Mosquito hotend for example.  I have tested Klipper also, but I like Reprap firmware more. Klipper is not ready yet, too much hassle..  RepRap is much more userfriendly. But maybe in the future it will be better then RepRap ;-)
Would me nice if you could post a message when you start modding your CB+
With kind regards,
;-) Arthur

**Comment by MichaelMartinez** [comment]
Fantastic Arthur... I will definitely share anything I create with you and @Battosai42 who also has a CB+ repo with mods.

**Comment by Battosai42** [comment]
I am currently using a modded V6 hotend on my CB+ which was already an improvement over the original one but i also think for a more extensive overhaul moving to something smaller might be prudent (Mosquito, Rapido or Revo), haven't decided yet.. 
In terms of the Firmware i also went with duet3 mini/reprap firmware, mostly because i can run it without a raspberry pi and i wanted to have an external WIFI antenna  as the CB+ is a metal box (this is doable on a  RP but needs a hardware mod to it). Since reprap firmware 3.4 now also supports input shaping i see no downside to that, in fact its the more capable firmware and better supported in most slicers.

**Comment by askmurphy** [comment]
We have also a discord channel: https://discord.gg/wHH9wdGs9D
